"""empty message

Revision ID: 5b7b9699d034
Revises: 
Create Date: 2024-05-04 19:07:55.655748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7b9699d034'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('niveau', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'moderateur', name='roleenum'), nullable=False),
    sa.Column('phoneNumber', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('domaine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomService', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accessToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Users_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Users_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planTarification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('type_tarification', sa.String(), nullable=True),
    sa.Column('tarif', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abonnementService',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('date_abonnement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['access_token_id'], ['accessToken.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planTarification.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abonnement_id', sa.Integer(), nullable=True),
    sa.Column('Moyen_paiement', sa.String(), nullable=True),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['abonnement_id'], ['abonnementService.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payement')
    op.drop_table('abonnementService')
    op.drop_table('planTarification')
    op.drop_table('accessToken')
    op.drop_table('service')
    op.drop_table('domaine')
    op.drop_table('Users')
    # ### end Alembic commands ###
